modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="m4r1os"
version="1.1.5"
displayName="FiveM-style HUD & Chat"
logoFile="logo.png"
authors="m4r1os, MNV, Saralis Dev"

description='''
FiveM-style HUD + chat messages for Minecraft.

Features:
- Rich markup (emoji/labels/boxes/colors)
- Staff-only routing / channels
- Clean, configurable dispatch-style messages
'''

[[dependencies.m4r1os]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.m4r1os]]
modId="minecraft"
mandatory=true
versionRange="[1.18)"
ordering="NONE"
side="BOTH"
